language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION update compile # TODO: test when scalacheck dependency is enabled
scala:
  - 2.10.3
  - 2.11.0-M6
jdk:
  - oraclejdk6
  - openjdk7
notifications:
  email:
    - qbranch@typesafe.com
