sudo: false

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test scalafmt::test test:scalafmt::test sbt:scalafmt::test

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.4
  - 2.13.0-M4

jdk:
  - oraclejdk8
