# Use container-based build
sudo: false

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - openjdk6

notifications:
  email:
    - sbt-dev-bot@googlegroups.com
